### ISSUE TITLE
SetInterval Function on API Call

### ISSUE THREAD

**Issue by RajisteB** [Cityslick/CryptoApp#3]
In my crypto-helper.js >>>

function callPrices() {
    setInterval(
        function getPrices(req, res, next) {
            cc.priceMulti(['BTC', 'BCH', 'ETH', 'LTC', 'XEM', 'XRP', 'DASH', 'ZEC', 'DGB'], ['USD'])
            .then(prices => {
                console.log(prices);
                res.locals = prices;
                return next();
            }).catch((err) => {
                console.log(err);
                next(err);
            });
        }, 3000);
}; 

In the log ->

TypeError: Cannot set property 'locals' of undefined
    at cc.priceMulti.then.prices (/Users/student_11/wdi/Projects/CryptoApp/services/crypto/crypto-helper.js:14:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
(node:65140) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 66): TypeError: next is not a function

**Comment by drew-mahrt** [comment]
There are two ways to handle this:

1. Move those api calls to the front-end js and call from there.

2. Set up routes to fetch and return the data, and call those routes from your front-end js. 

Either way, your front-end needs to be making the calls to request the data, because this isn't like a socket that remains open after a response is sent. The client needs to make the request each time.
